version: '3'
services:
    mongo-shard-setup:
        container_name: "mongo-shard-setup34"
        image: mongo:4.0.1
        #depends_on:
        #    - "mongo-router"
        #links:
        #    - mongo-router:mongo-router
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGOS=mongo-router
            - MONGO11=mongo-3-1
            - MONGO12=mongo-3-2
            - MONGO13=mongo-3-3
            - MONGO21=mongo-4-1
            - MONGO22=mongo-4-2
            - MONGO23=mongo-4-3
            - RS3=rs3
            - RS4=rs4
            - PORT=27017
            - PORT1=27017
            - PORT2=27017
            - PORT3=27017
        entrypoint: [ "/scripts/init-shard34.sh" ]
        restart: on-failure:20
