version: '3'
services:
    mongo-4-2:
        container_name: "mongo-4-2"
        image: mongo:4.0.1
        ports:
            - "30022:27017"
        command: mongod --replSet rs4 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-4-3:
        container_name: "mongo-4-3"
        image: mongo:4.0.1
        ports:
            - "30023:27017"
        command: mongod --replSet rs4 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-4-1:
        container_name: "mongo-4-1"
        image: mongo:4.0.1
        ports:
            - "30021:27017"
        command: mongod --replSet rs4 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-4-2:mongo-4-2
            - mongo-4-3:mongo-4-3
        restart: always

    mongo-rs4-setup:
        container_name: "mongo-rs4-setup"
        image: mongo:4.0.1
        depends_on:
            - "mongo-4-1"
            - "mongo-4-2"
            - "mongo-4-3"
        links:
            - mongo-4-1:mongo-4-1
            - mongo-4-2:mongo-4-2
            - mongo-4-3:mongo-4-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-4-1
            - MONGO2=mongo-4-2
            - MONGO3=mongo-4-3
            - RS=rs4
        entrypoint: [ "/scripts/setup.sh" ]

        
